### PR TITLE
Various contributions

### PR DESCRIPTION
**Pull request by torarnv**
These are some changes I've made as I'm trying to integrate WP-Simple-Pay-Lite-for-Stripe in our site. Let me know what you think! :smile:

### CODE REVIEW

**Comment by pderksen** [comment]
@torarnv Sorry for the delay. We're ready to start merging in what makes sense.

Could you submit the PR against the branch https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/tree/pr/17 so we can thoroughly test each addition? Thanks.

**Comment by pderksen** [comment]
Closing this due to delay and the fact that we're in the middle of a rewrite of the plugin.

**Comment by torarnv** [comment]
Sorry for the delay, when is the rewrite going to be done roughly? I can wait with these and see if they are still issues when the new plugin is done?

**Comment by pderksen** [comment]
@torarnv Probably within the next month or two. We're rewriting and testing our Pro plugin first, then with the shared functionality we'll port over what makes sense to Lite. Thanks.

**Pull request closed without merging**
